//+20
List<Map<String, dynamic>> countryPhoneData = [
  {"country_name_en": "United Arab Emirates", "country_name_ar": "الإمارات", "country_code": "+971", "country_short": "AE", "flag": "🇦🇪", "min_length": 9, "max_length": 9},
  {"country_name_en": "Bahrain", "country_name_ar": "البحرين", "country_code": "+973", "country_short": "BH", "flag": "🇧🇭", "min_length": 8, "max_length": 8},
  {"country_name_en": "Algeria", "country_name_ar": "الجزائر", "country_code": "+213", "country_short": "DZ", "flag": "🇩🇿", "min_length": 9, "max_length": 10},
  {"country_name_en": "Egypt", "country_name_ar": "مصر", "country_code": "+20", "country_short": "EG", "flag": "🇪🇬", "min_length": 10, "max_length": 11},
  {"country_name_en": "Iraq", "country_name_ar": "العراق", "country_code": "+964", "country_short": "IQ", "flag": "🇮🇶", "min_length": 10, "max_length": 10},
  {"country_name_en": "Jordan", "country_name_ar": "الأردن", "country_code": "+962", "country_short": "JO", "flag": "🇯🇴", "min_length": 9, "max_length": 9},
  {"country_name_en": "Kuwait", "country_name_ar": "الكويت", "country_code": "+965", "country_short": "KW", "flag": "🇰🇼", "min_length": 8, "max_length": 8},
  {"country_name_en": "Lebanon", "country_name_ar": "لبنان", "country_code": "+961", "country_short": "LB", "flag": "🇱🇧", "min_length": 7, "max_length": 8},
  {"country_name_en": "Libya", "country_name_ar": "ليبيا", "country_code": "+218", "country_short": "LY", "flag": "🇱🇾", "min_length": 9, "max_length": 9},
  {"country_name_en": "Morocco", "country_name_ar": "المغرب", "country_code": "+212", "country_short": "MA", "flag": "🇲🇦", "min_length": 9, "max_length": 9},
  {"country_name_en": "Mauritania", "country_name_ar": "موريتانيا", "country_code": "+222", "country_short": "MR", "flag": "🇲🇷", "min_length": 7, "max_length": 9},
  {"country_name_en": "Oman", "country_name_ar": "عمان", "country_code": "+968", "country_short": "OM", "flag": "🇴🇲", "min_length": 8, "max_length": 8},
  {"country_name_en": "Palestine", "country_name_ar": "فلسطين", "country_code": "+970", "country_short": "PS", "flag": "🇵🇸", "min_length": 8, "max_length": 9},
  {"country_name_en": "Qatar", "country_name_ar": "قطر", "country_code": "+974", "country_short": "QA", "flag": "🇶🇦", "min_length": 8, "max_length": 8},
  {"country_name_en": "Saudi Arabia", "country_name_ar": "السعودية", "country_code": "+966", "country_short": "SA", "flag": "🇸🇦", "min_length": 9, "max_length": 9},
  {"country_name_en": "Sudan", "country_name_ar": "السودان", "country_code": "+249", "country_short": "SD", "flag": "🇸🇩", "min_length": 9, "max_length": 10},
  {"country_name_en": "Somalia", "country_name_ar": "الصومال", "country_code": "+252", "country_short": "SO", "flag": "🇸🇴", "min_length": 7, "max_length": 10},
  {"country_name_en": "Syria", "country_name_ar": "سوريا", "country_code": "+963", "country_short": "SY", "flag": "🇸🇾", "min_length": 9, "max_length": 9},
  {"country_name_en": "Tunisia", "country_name_ar": "تونس", "country_code": "+216", "country_short": "TN", "flag": "🇹🇳", "min_length": 8, "max_length": 8},
  {"country_name_en": "Yemen", "country_name_ar": "اليمن", "country_code": "+967", "country_short": "YE", "flag": "🇾🇪", "min_length": 9, "max_length": 9},
  {"country_name_en": "Djibouti", "country_name_ar": "جيبوتي", "country_code": "+253", "country_short": "DJ", "flag": "🇩🇯", "min_length": 8, "max_length": 8},
  {"country_name_en": "Comoros", "country_name_ar": "جزر القمر", "country_code": "+269", "country_short": "KM", "flag": "🇰🇲", "min_length": 7, "max_length": 10},
];
